---
version: '3'

services:
  app:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USERNAME=psqluser
      - DB_DATABASE=appdb
      - DB_PASSWORD=password123
    volumes:
      - './app:/app'
    depends_on:
      - postgresql
    networks:
      - app-net


  postgresql:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    environment:
      #- 'ALLOW_EMPTY_PASSWORD=yes'
      - POSTGRESQL_USER=psqluser
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_PASSWORD=password123
    networks:
      - app-net


volumes:
  postgresql_data:
    driver: local
  app:
    driver: local

networks:
  app-net:
    driver: bridge
