---
version: '3'

services:
  php:
    build:
      context: .
    ports:
      - '80:80'
#    environment:
#      - DB_HOST=postgresql
#      - DB_PORT=5432
#      - DB_USERNAME=psqluser
#      - DB_DATABASE=appdb
#      - DB_PASSWORD=password123
    volumes:
      - './app:/var/www/html'
    depends_on:
      - postgresql
    networks:
      - app-net


  postgresql:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    environment:
      #- 'ALLOW_EMPTY_PASSWORD=yes'
      - POSTGRES_USER=psqluser
      - POSTGRES_DATABASE=appdb
      - POSTGRES_PASSWORD=password123
    networks:
      - app-net


volumes:
  postgresql_data:
    driver: local
  app:
    driver: local

networks:
  app-net:
    driver: bridge
